---
# tasks file for elasticsearch-ingest-openstack
- name: Put grok processor ingest
  uri:
    url: "http://{{ inventory_hostname }}:9200/_ingest/pipeline/openstackgrok/"
    method: PUT
    body: "{{ lookup('file','pipelines.json') }}"
    status_code: 200
    body_format: json