---
# tasks file for logstash
- name: Update repositories cache and install "logstash" package
  apt:
    name: logstash
    state: present
    update_cache: yes
  notify:
    - restart logstash

- name: Enable logstash to start on boot
  service:
    name: logstash
    enabled: yes
    state: started