---
# tasks file for elastic5x
- name: Add Elastic PGP key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Installing apt transport https
  apt:
    name: apt-transport-https
    state: present

- name: Add elastic 5.x repository.
  apt_repository: 
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present 
    filename: elastic-5.x
    update_cache: yes