---
- hosts: kibana
  vars_files:
     - vars.yml
  tasks:
  - name: Update repositories cache and install "kibana" package
    apt:
      name: kibana
      update_cache: yes

  - name: Template kibana config
    template:
      src: ./j2/kibana.yml.j2
      dest: /etc/kibana/kibana.yml
    notify:
      - restart kibana
  
  - name: Enable kibana to start on boot
    service:
      name: kibana
      enabled: yes
      state: started
  
  handlers:
    - name: restart kibana
      service: 
        name: kibana
        state: restarted