---
- hosts: novacompute
  vars_files:
     - vars.yml
  tasks:
  - name: Install deb package for metricbeat
    apt:
      deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-5.5.0-amd64.deb
  - name: Template metricbeat config
    template:
      src: ./j2/metricbeat_config.j2
      dest: /etc/metricbeat/metricbeat.yml
    notify:
      - restart metricbeat 
  - name: ensure metricbeat is running (and enable it at boot)
    service: 
      name: metricbeat 
      state: started
      enabled: yes
  handlers:
    - name: restart metricbeat
      service: 
        name: metricbeat 
        state: restarted