---
- hosts: all
  gather_facts: false
  become: true
  roles:
    - python

- hosts: all
  gather_facts: true

- hosts: elasticsearch
  become: true
  vars:
    cluster_name: openstack
    es_heap_size: 2g
  roles:
    - java8
    - elastic5x

- hosts: elasticsearch
  serial: 1
  become: true
  vars:
    cluster_name: openstack
    es_heap_size: 2g
  roles:
    - elasticsearch

- hosts: elasticsearch
  become: true
  vars:
    machine_role: elasticsearch
  roles:
    - metricbeat
    - filebeat

- hosts: kibana
  become: true
  vars:
    kibana_port: 5601
  roles:
    - elastic5x
    - kibana

- hosts: curator
  become: true
  vars:
    delete_older_than_days: 1
  roles:
    - curator
  tags:
    - curator

- hosts: elasticsearch[0]
  become: true
  roles:
    - elasticsearch-ingest-openstack

- hosts: elasticsearch[0]
  tasks: 
  - name: import metricbeats dashboards to kibana
    shell: /usr/share/metricbeat/scripts/import_dashboards
  - name: import filebeat dashboards to kibana
    shell: /usr/share/filebeat/scripts/import_dashboards
  
- hosts: openstack
  become: true
  vars:
    machine_role: openstack
  roles:
    - metricbeat
    - openstack