---
- hosts: all
  gather_facts: false
  become: true
  roles:
    - python

- hosts: elasticsearch
  become: true
  vars:
    cluster_name: openstack_test
    es_heap_size: 2g
  roles:
    - java8
    - elastic5x
    - elasticsearch

- hosts: kibana
  become: true
  vars:
    kibana_port: 5601
  roles:
    - elastic5x
    - kibana

- hosts: compute
  become: true
  roles:
    - elastic5x
    - metricbeat
    - filebeat

- hosts: compute[0]
  tasks: 
  - name: import metricbeats dashboards to kibana
    shell: /usr/share/metricbeat/scripts/import_dashboards
  - name: import filebeat dashboards to kibana
    shell: /usr/share/filebeat/scripts/import_dashboards