---
- hosts: elasticsearch
  roles:
    - java8
    - elastic5x
    - elasticsearch

- hosts: kibana
  vars:
    kibana_port: 9000
  roles:
    - elastic5x
    - kibana

- hosts: all
  roles:
    - metricbeat