---
# tasks file for kibana
- name: Update repositories cache and install "kibana" package
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Template kibana config
  template:
    src: ./templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify:
    - restart kibana

- name: Enable kibana to start on boot
  service:
    name: kibana
    enabled: yes
    state: started