---
# tasks file for packetbeat
- name: Install deb package for packetbeat
  apt:
    deb: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-5.6.3-amd64.deb
    state: present

- name: Template packetbeat config
  template:
    src: ./templates/packetbeat.yml
    dest: /etc/packetbeat/packetbeat.yml
  notify:
    - restart packetbeat

- name: Ensure packetbeat is running (and enable it at boot)
  service: 
    name: packetbeat
    enabled: yes
  notify:
    - restart packetbeat