# From example_rules/example_frequency.yaml
es_host: {{ groups['elasticsearch'][0] }}
es_port: 9200
name: Example rule
type: frequency
index: metricbeat-*
num_events: 3
timeframe:
    minutes: 3
filter:
- term:
    some_field: "some_value"
alert:
- "email"
email:
- "yhtan@palo-it.com"