---
# tasks file for elasticsearch
- name: Add Elastic PGP key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Installing apt transport https
  apt:
    name: apt-transport-https
    state: present

- name: Add elastic 5.x repository.
  apt_repository: 
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present 
    filename: elastic-5.x
    update_cache: yes

- name: Update repositories cache and install "elasticsearch" package
  apt:
    name: elasticsearch
    update_cache: yes

- name: Template elasticsearch config
  template:
    src: ./templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch

- name: Template jvm options config
  template:
    src: ./templates/jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
  notify:
    - restart elasticsearch

- name: Enable elasticsearch to start on boot
  service:
    name: elasticsearch
    enabled: yes
    state: started